DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS shoe_listings CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS favourites CASCADE;


CREATE TABLE users(id SERIAL PRIMARY KEY NOT NULL,
email VARCHAR(500) NOT NULL,
password VARCHAR(500) NOT NULL,
name VARCHAR(500) NOT NULL,
is_admin BOOLEAN NOT NULL DEFAULT FALSE);

CREATE TABLE shoe_listings(id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
title VARCHAR(100) NOT NULL,
description TEXT,
brand VARCHAR(50) NOT NULL,
is_featured BOOLEAN NOT NULL DEFAULT FALSE,
size SMALLINT NOT NULL,
price INT NOT NULL,
condition VARCHAR(50),
is_sold BOOLEAN NOT NULL DEFAULT FALSE,
city VARCHAR(100) NOT NULL,
postal_code VARCHAR(50) NOT NULL,
thumbnail_url VARCHAR(200) NOT NULL,
cover_url VARCHAR(200) NOT NULL,
is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE messages(id SERIAL PRIMARY KEY NOT NULL,
shoe_listings_id INTEGER REFERENCES shoe_listings(id) ON DELETE CASCADE NOT NULL,
sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
content TEXT NOT NULL,
timestamp TIMESTAMP NOT NULL);

CREATE TABLE favourites(id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
shoe_listings_id INTEGER NOT NULL REFERENCES shoe_listings(id) ON DELETE CASCADE);
