DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(id SERIAL PRIMARY KEY NOT NULL,
email VARCHAR(500) NOT NULL,
password VARCHAR(500) NOT NULL,
name VARCHAR(500) NOT NULL,
is_admin BOOLEAN NOT NULL DEFAULT FALSE);
