DROP TABLE IF EXISTS favourites CASCADE;


CREATE TABLE favourites(id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
shoe_listings_id INTEGER NOT NULL REFERENCES shoe_listings(id) ON DELETE CASCADE);
